### ISSUE TITLE
Failed to use FID sensitivity heatmaps 

### ISSUE THREAD

**Issue by 49xxy** [kynkaat/role-of-imagenet-classes-in-fid#1]
Thank you for your excellent work.
When using FID sensitivity heatmaps tool for my data set, I encountered the following problems.

`Downloading inception_v3-tf-2015-12-05.pkl skipped; already exists in ./.pickles/
Computing real features...
Traceback (most recent call last):
  File "generate_heatmaps.py", line 69, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "generate_heatmaps.py", line 56, in main
    visualize_heatmaps(results_dir=results_dir,
  File "/content/drive/MyDrive/role-of-imagenet-classes-in-fid-master/fid_heatmaps/sensitivity_heatmaps.py", line 62, in visualize_heatmaps
    for images, _ in dataloader:
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/role-of-imagenet-classes-in-fid-master/dataset.py", line 88, in __getitem__
    image = self._load_raw_image(self._raw_idx[idx])
IndexError: index 7120 is out of bounds for axis 0 with size 7120`

I sincerely hope to get your help！

**Comment by kynkaat** [comment]
Hello,

Thank you for your interest and reporting this. My bad, I forgot to add an option to control the zip dataset size in `generate_heatmaps.py`. You can now use the `--num_images` argument of `generate_heatmaps.py` to provide how many images you have in your zip dataset.

**Comment by kynkaat** [comment]
Closing this, see https://github.com/kynkaat/role-of-imagenet-classes-in-fid/commit/1fbde80be38375e6fdbf67d93eaf7035067aeba0.
